//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office365FiddlerExtension.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Office365FiddlerExtension.Language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 OK - APACHE AUTODISCOVER.
        /// </summary>
        internal static string _200_OK___APACHE_AUTODISCOVER {
            get {
                return ResourceManager.GetString("200 OK - APACHE AUTODISCOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Session Analysis.
        /// </summary>
        internal static string All_Session_Analysis {
            get {
                return ResourceManager.GetString("All Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze All Sessions.
        /// </summary>
        internal static string Analyze_All_Sessions {
            get {
                return ResourceManager.GetString("Analyze All Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Selected Sessions.
        /// </summary>
        internal static string Analyze_Selected_Sessions {
            get {
                return ResourceManager.GetString("Analyze Selected Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APACHE.
        /// </summary>
        internal static string APACHE {
            get {
                return ResourceManager.GetString("APACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APACHE AUTODISCOVER.
        /// </summary>
        internal static string APACHE_AUTODISCOVER {
            get {
                return ResourceManager.GetString("APACHE AUTODISCOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;An Apache Web Server (Unix/Linux) is answering Autodiscover requests!&lt;/span&gt;&lt;/b&gt;&lt;p&gt;This should not be happening. Consider disabling Root Domain Autodiscover lookups.&lt;/p&gt;&lt;p&gt;See ExcludeHttpsRootDomain on &lt;/p&gt;&lt;p&gt;&lt;a href=&apos;https://support.microsoft.com/en-us/help/2212902/unexpected-autodiscover-behavior-when-you-have-registry-settings-under&apos; target=&apos;_blank&apos;&gt;https://support.microsoft.com/en-us/help/2212902/unexpected-autodiscover-behavior-when-you-have-registry-settings-under &lt;/a&gt;&lt;/p&gt;&lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Apache_AutoDiscover_Response_Comments {
            get {
                return ResourceManager.GetString("Apache AutoDiscover Response Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache is answering Autodiscover requests!.
        /// </summary>
        internal static string Apache_is_answering_Autodiscover_requests_ {
            get {
                return ResourceManager.GetString("Apache is answering Autodiscover requests!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Name Immutable ID.
        /// </summary>
        internal static string Attribute_Name_Immutable_ID {
            get {
                return ResourceManager.GetString("Attribute Name Immutable ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Name UPN.
        /// </summary>
        internal static string Attribute_Name_UPN {
            get {
                return ResourceManager.GetString("Attribute Name UPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broad Logic Checks.
        /// </summary>
        internal static string Broad_Logic_Checks {
            get {
                return ResourceManager.GetString("Broad Logic Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture was.
        /// </summary>
        internal static string Capture_was {
            get {
                return ResourceManager.GetString("Capture was", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates every.
        /// </summary>
        internal static string Check_for_updates_every {
            get {
                return ResourceManager.GetString("Check for updates every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected Sessions.
        /// </summary>
        internal static string Clear_Selected_Sessions {
            get {
                return ResourceManager.GetString("Clear Selected Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link below for update instructions.
        /// </summary>
        internal static string Click_the_link_below_for_update_instructions {
            get {
                return ResourceManager.GetString("Click the link below for update instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Begin Request.
        /// </summary>
        internal static string Client_Begin_Request {
            get {
                return ResourceManager.GetString("Client Begin Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connected.
        /// </summary>
        internal static string Client_Connected {
            get {
                return ResourceManager.GetString("Client Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Done Response.
        /// </summary>
        internal static string Client_Done_Response {
            get {
                return ResourceManager.GetString("Client Done Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concerning.
        /// </summary>
        internal static string Concerning {
            get {
                return ResourceManager.GetString("Concerning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and save the below text into a .cer file to view the signing certificate..
        /// </summary>
        internal static string Copy_Save_Signing_Certificate {
            get {
                return ResourceManager.GetString("Copy Save Signing Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        internal static string Elapsed_Time {
            get {
                return ResourceManager.GetString("Elapsed Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension DLL.
        /// </summary>
        internal static string Extension_DLL {
            get {
                return ResourceManager.GetString("Extension DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Enabled.
        /// </summary>
        internal static string Extension_Enabled {
            get {
                return ResourceManager.GetString("Extension Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Options.
        /// </summary>
        internal static string ExtensionOptions {
            get {
                return ResourceManager.GetString("ExtensionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Path.
        /// </summary>
        internal static string ExtensionPath {
            get {
                return ResourceManager.GetString("ExtensionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Positive.
        /// </summary>
        internal static string False_Positive {
            get {
                return ResourceManager.GetString("False Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiddler Begin Request.
        /// </summary>
        internal static string Fiddler_Begin_Request {
            get {
                return ResourceManager.GetString("Fiddler Begin Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiddler Update Check.
        /// </summary>
        internal static string Fiddler_Update_Check {
            get {
                return ResourceManager.GetString("Fiddler Update Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For an explantion of session timers refer to:.
        /// </summary>
        internal static string For_an_explantion_of_session_timers_refer_to {
            get {
                return ResourceManager.GetString("For an explantion of session timers refer to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Session Data.
        /// </summary>
        internal static string General_Session_Data {
            get {
                return ResourceManager.GetString("General Session Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Extension Version.
        /// </summary>
        internal static string Github_Extension_Version {
            get {
                return ResourceManager.GetString("Github Extension Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Information.
        /// </summary>
        internal static string Github_Information {
            get {
                return ResourceManager.GetString("Github Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Ruleset Version.
        /// </summary>
        internal static string Github_Ruleset_Version {
            get {
                return ResourceManager.GetString("Github Ruleset Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Request Headers.
        /// </summary>
        internal static string Got_Request_Headers {
            get {
                return ResourceManager.GetString("Got Request Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Response Headers.
        /// </summary>
        internal static string Got_Response_Headers {
            get {
                return ResourceManager.GetString("Got Response Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string Grey {
            get {
                return ResourceManager.GetString("Grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host IP.
        /// </summary>
        internal static string Host_IP {
            get {
                return ResourceManager.GetString("Host IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        internal static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        internal static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Extension Version.
        /// </summary>
        internal static string Local_Extension_Version {
            get {
                return ResourceManager.GetString("Local Extension Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Ruleset Version.
        /// </summary>
        internal static string Local_Ruleset_Version {
            get {
                return ResourceManager.GetString("Local Ruleset Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locally Installed Information.
        /// </summary>
        internal static string Locally_Installed_Information {
            get {
                return ResourceManager.GetString("Locally Installed Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeing many or few of these? Either way these aren&apos;t typical Microsoft365 traffic sessions. They may be an indication of a proxy client forcing traffic down a certain network path? If there&apos;s no Microsoft365 client traffic in this Fiddler trace and it&apos;s suspected this could be a factor, change your network, try a different machine without any proxy client / proxy configuration in place..
        /// </summary>
        internal static string Loopback_Tunnel_Response_Comments {
            get {
                return ResourceManager.GetString("Loopback Tunnel Response Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute ago.
        /// </summary>
        internal static string minute_ago {
            get {
                return ResourceManager.GetString("minute ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        internal static string minutes_ago {
            get {
                return ResourceManager.GetString("minutes ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Identifier Format.
        /// </summary>
        internal static string Name_Identifier_Format {
            get {
                return ResourceManager.GetString("Name Identifier Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Update Check.
        /// </summary>
        internal static string Next_Update_Check {
            get {
                return ResourceManager.GetString("Next Update Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session analysis. Use the &apos;Process All Sessions&apos; option from the Office365 extension menu to get session analysis..
        /// </summary>
        internal static string No_Session_Analysis {
            get {
                return ResourceManager.GetString("No Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obscure Settings.
        /// </summary>
        internal static string Obscure_Settings {
            get {
                return ResourceManager.GetString("Obscure Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365.
        /// </summary>
        internal static string Office_365 {
            get {
                return ResourceManager.GetString("Office 365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365 Fiddler Extension.
        /// </summary>
        internal static string Office_365_Fiddler_Extension {
            get {
                return ResourceManager.GetString("Office 365 Fiddler Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Live Trace.
        /// </summary>
        internal static string On_Live_Trace {
            get {
                return ResourceManager.GetString("On Live Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Load Saz.
        /// </summary>
        internal static string On_Load_Saz {
            get {
                return ResourceManager.GetString("On Load Saz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Demand.
        /// </summary>
        internal static string OnDemand {
            get {
                return ResourceManager.GetString("OnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Session Timers.
        /// </summary>
        internal static string Overall_Session_Timers {
            get {
                return ResourceManager.GetString("Overall Session Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Selected Sessions.
        /// </summary>
        internal static string Recalculate_Selected_Sessions {
            get {
                return ResourceManager.GetString("Recalculate Selected Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        internal static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Capture.
        /// </summary>
        internal static string Remote_Capture {
            get {
                return ResourceManager.GetString("Remote Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issues.
        /// </summary>
        internal static string Report_Issues {
            get {
                return ResourceManager.GetString("Report Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Code.
        /// </summary>
        internal static string Response_Code {
            get {
                return ResourceManager.GetString("Response Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Server.
        /// </summary>
        internal static string Response_Server {
            get {
                return ResourceManager.GetString("Response Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAML Response Parser.
        /// </summary>
        internal static string SAML_Response_Parser {
            get {
                return ResourceManager.GetString("SAML Response Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreForSession.
        /// </summary>
        internal static string ScoreForSession {
            get {
                return ResourceManager.GetString("ScoreForSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Begin Response.
        /// </summary>
        internal static string Server_Begin_Response {
            get {
                return ResourceManager.GetString("Server Begin Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Done Response.
        /// </summary>
        internal static string Server_Done_Response {
            get {
                return ResourceManager.GetString("Server Done Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Got Request.
        /// </summary>
        internal static string Server_Got_Request {
            get {
                return ResourceManager.GetString("Server Got Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Think Time.
        /// </summary>
        internal static string Server_Think_Time {
            get {
                return ResourceManager.GetString("Server Think Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Timers.
        /// </summary>
        internal static string Server_Timers {
            get {
                return ResourceManager.GetString("Server Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Age.
        /// </summary>
        internal static string Session_Age {
            get {
                return ResourceManager.GetString("Session Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Analysis.
        /// </summary>
        internal static string Session_Analysis {
            get {
                return ResourceManager.GetString("Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Captured.
        /// </summary>
        internal static string Session_Captured {
            get {
                return ResourceManager.GetString("Session Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session collected within 7 days, data freshness is good. Best case scenario for correlating this data to backend server logs..
        /// </summary>
        internal static string Session_collected_within_7_days {
            get {
                return ResourceManager.GetString("Session collected within 7 days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID.
        /// </summary>
        internal static string Session_ID {
            get {
                return ResourceManager.GetString("Session ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Type.
        /// </summary>
        internal static string Session_Type {
            get {
                return ResourceManager.GetString("Session Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Session Severity.
        /// </summary>
        internal static string Set_Session_Severity {
            get {
                return ResourceManager.GetString("Set Session Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe.
        /// </summary>
        internal static string Severe {
            get {
                return ResourceManager.GetString("Severe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Running Session Threshold.
        /// </summary>
        internal static string Slow_Running_Session_Threshold {
            get {
                return ResourceManager.GetString("Slow Running Session Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Session Analysis.
        /// </summary>
        internal static string Some_Session_Analysis {
            get {
                return ResourceManager.GetString("Some Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Fiddler itself checking for updates..
        /// </summary>
        internal static string This_is_Fiddler_itself_checking_for_updates_ {
            get {
                return ResourceManager.GetString("This is Fiddler itself checking for updates.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit Time.
        /// </summary>
        internal static string Transit_Time {
            get {
                return ResourceManager.GetString("Transit Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninteresting.
        /// </summary>
        internal static string Uninteresting {
            get {
                return ResourceManager.GetString("Uninteresting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To Date.
        /// </summary>
        internal static string Up_To_Date {
            get {
                return ResourceManager.GetString("Up To Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string Update_Available {
            get {
                return ResourceManager.GetString("Update Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Session Time Threshold.
        /// </summary>
        internal static string Warning_Session_Time_Threshold {
            get {
                return ResourceManager.GetString("Warning Session Time Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are these two thresholds?.
        /// </summary>
        internal static string What_are_these_two_thresholds {
            get {
                return ResourceManager.GetString("What are these two thresholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is ScoreForSession?.
        /// </summary>
        internal static string What_is_ScoreForSession {
            get {
                return ResourceManager.GetString("What is ScoreForSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
    }
}
