//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office365FiddlerExtension.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Office365FiddlerExtension.Language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Session Analysis.
        /// </summary>
        internal static string All_Session_Analysis {
            get {
                return ResourceManager.GetString("All Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze All Sessions.
        /// </summary>
        internal static string Analyze_All_Sessions {
            get {
                return ResourceManager.GetString("Analyze All Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Selected Sessions.
        /// </summary>
        internal static string Analyze_Selected_Sessions {
            get {
                return ResourceManager.GetString("Analyze Selected Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Name Immutable ID.
        /// </summary>
        internal static string Attribute_Name_Immutable_ID {
            get {
                return ResourceManager.GetString("Attribute Name Immutable ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Name UPN.
        /// </summary>
        internal static string Attribute_Name_UPN {
            get {
                return ResourceManager.GetString("Attribute Name UPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broad Logic Checks.
        /// </summary>
        internal static string Broad_Logic_Checks {
            get {
                return ResourceManager.GetString("Broad Logic Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 OK - APACHE AUTODISCOVER.
        /// </summary>
        internal static string BroadLogicChecks_200_OK___APACHE_AUTODISCOVER {
            get {
                return ResourceManager.GetString("BroadLogicChecks_200 OK - APACHE AUTODISCOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APACHE.
        /// </summary>
        internal static string BroadLogicChecks_APACHE {
            get {
                return ResourceManager.GetString("BroadLogicChecks_APACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APACHE AUTODISCOVER.
        /// </summary>
        internal static string BroadLogicChecks_APACHE_AUTODISCOVER {
            get {
                return ResourceManager.GetString("BroadLogicChecks_APACHE AUTODISCOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;An Apache Web Server (Unix/Linux) is answering Autodiscover requests!&lt;/span&gt;&lt;/b&gt;&lt;p&gt;This should not be happening. Consider disabling Root Domain Autodiscover lookups.&lt;/p&gt;&lt;p&gt;See ExcludeHttpsRootDomain on &lt;/p&gt;&lt;p&gt;&lt;a href=&apos;https://support.microsoft.com/en-us/help/2212902/unexpected-autodiscover-behavior-when-you-have-registry-settings-under&apos; target=&apos;_blank&apos;&gt;https://support.microsoft.com/en-us/help/2212902/unexpected-autodiscover-behavior-when-you-have-registry-settings-under &lt;/a&gt;&lt;/p&gt;&lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BroadLogicChecks_Apache_AutoDiscover_Response_Comments {
            get {
                return ResourceManager.GetString("BroadLogicChecks_Apache AutoDiscover Response Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache is answering Autodiscover requests!.
        /// </summary>
        internal static string BroadLogicChecks_Apache_is_answering_Autodiscover_requests_ {
            get {
                return ResourceManager.GetString("BroadLogicChecks_Apache is answering Autodiscover requests!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiddler Update Check.
        /// </summary>
        internal static string BroadLogicChecks_Fiddler_Update_Check {
            get {
                return ResourceManager.GetString("BroadLogicChecks_Fiddler Update Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeing many or few of these? Either way these aren&apos;t typical Microsoft365 traffic sessions. They may be an indication of a proxy client forcing traffic down a certain network path? If there&apos;s no Microsoft365 client traffic in this Fiddler trace and it&apos;s suspected this could be a factor, change your network, try a different machine without any proxy client / proxy configuration in place..
        /// </summary>
        internal static string BroadLogicChecks_Loopback_Tunnel_Response_Comments {
            get {
                return ResourceManager.GetString("BroadLogicChecks_Loopback Tunnel Response Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loopback Tunnel.
        /// </summary>
        internal static string BroadLogicChecks_LoopbackTunnel {
            get {
                return ResourceManager.GetString("BroadLogicChecks_LoopbackTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Fiddler itself checking for updates..
        /// </summary>
        internal static string BroadLogicChecks_This_is_Fiddler_itself_checking_for_updates_ {
            get {
                return ResourceManager.GetString("BroadLogicChecks_This is Fiddler itself checking for updates.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture was.
        /// </summary>
        internal static string Capture_was {
            get {
                return ResourceManager.GetString("Capture was", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates every.
        /// </summary>
        internal static string Check_for_updates_every {
            get {
                return ResourceManager.GetString("Check for updates every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected Sessions.
        /// </summary>
        internal static string Clear_Selected_Sessions {
            get {
                return ResourceManager.GetString("Clear Selected Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link below for update instructions.
        /// </summary>
        internal static string Click_the_link_below_for_update_instructions {
            get {
                return ResourceManager.GetString("Click the link below for update instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Begin Request.
        /// </summary>
        internal static string Client_Begin_Request {
            get {
                return ResourceManager.GetString("Client Begin Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connected.
        /// </summary>
        internal static string Client_Connected {
            get {
                return ResourceManager.GetString("Client Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Done Response.
        /// </summary>
        internal static string Client_Done_Response {
            get {
                return ResourceManager.GetString("Client Done Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concerning.
        /// </summary>
        internal static string Concerning {
            get {
                return ResourceManager.GetString("Concerning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and save the below text into a .cer file to view the signing certificate..
        /// </summary>
        internal static string Copy_Save_Signing_Certificate {
            get {
                return ResourceManager.GetString("Copy Save Signing Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        internal static string Elapsed_Time {
            get {
                return ResourceManager.GetString("Elapsed Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension DLL.
        /// </summary>
        internal static string Extension_DLL {
            get {
                return ResourceManager.GetString("Extension DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Enabled.
        /// </summary>
        internal static string Extension_Enabled {
            get {
                return ResourceManager.GetString("Extension Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Options.
        /// </summary>
        internal static string ExtensionOptions {
            get {
                return ResourceManager.GetString("ExtensionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Path.
        /// </summary>
        internal static string ExtensionPath {
            get {
                return ResourceManager.GetString("ExtensionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Positive.
        /// </summary>
        internal static string False_Positive {
            get {
                return ResourceManager.GetString("False Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiddler Begin Request.
        /// </summary>
        internal static string Fiddler_Begin_Request {
            get {
                return ResourceManager.GetString("Fiddler Begin Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For an explantion of session timers refer to:.
        /// </summary>
        internal static string For_an_explantion_of_session_timers_refer_to {
            get {
                return ResourceManager.GetString("For an explantion of session timers refer to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Session Data.
        /// </summary>
        internal static string General_Session_Data {
            get {
                return ResourceManager.GetString("General Session Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Extension Version.
        /// </summary>
        internal static string Github_Extension_Version {
            get {
                return ResourceManager.GetString("Github Extension Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Information.
        /// </summary>
        internal static string Github_Information {
            get {
                return ResourceManager.GetString("Github Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Ruleset Version.
        /// </summary>
        internal static string Github_Ruleset_Version {
            get {
                return ResourceManager.GetString("Github Ruleset Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Request Headers.
        /// </summary>
        internal static string Got_Request_Headers {
            get {
                return ResourceManager.GetString("Got Request Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Response Headers.
        /// </summary>
        internal static string Got_Response_Headers {
            get {
                return ResourceManager.GetString("Got Response Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string Grey {
            get {
                return ResourceManager.GetString("Grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host IP.
        /// </summary>
        internal static string Host_IP {
            get {
                return ResourceManager.GetString("Host IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RESPONSE.
        /// </summary>
        internal static string HTTP_0_Authentication {
            get {
                return ResourceManager.GetString("HTTP_0 Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RESPONSE.
        /// </summary>
        internal static string HTTP_0_ResonseServer {
            get {
                return ResourceManager.GetString("HTTP_0 ResonseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;HTTP 0 - No Response&lt;/span&gt;&lt;/b&gt;.
        /// </summary>
        internal static string HTTP_0_Response_Alert {
            get {
                return ResourceManager.GetString("HTTP_0 Response Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 No Response.
        /// </summary>
        internal static string HTTP_0_ResponseCodeDescription {
            get {
                return ResourceManager.GetString("HTTP_0 ResponseCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of these types of server errors need to be considered in context with what you are troubleshooting and whether these are relevant or not. A small number is probably not an issue, larger numbers of these could be cause for concern.&lt;p&gt;If you are not seeing expected client traffic, consider if network traces should be collected. Review if there is an underlying network issue such as congestion on routers, which could be causing issues. The Network Connection Status Indicator (NCSI) on the client c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTTP_0_ResponseComments {
            get {
                return ResourceManager.GetString("HTTP_0 ResponseComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RESPONSE.
        /// </summary>
        internal static string HTTP_0_SessionType {
            get {
                return ResourceManager.GetString("HTTP_0 SessionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP 200 Actually OK. No errors, failed, or exceptions found in response body..
        /// </summary>
        internal static string HTTP_200_Actually_OK_ResponseAlert {
            get {
                return ResourceManager.GetString("HTTP_200_Actually_OK ResponseAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 Actually OK.
        /// </summary>
        internal static string HTTP_200_Actually_OK_ResponseCodeDescription {
            get {
                return ResourceManager.GetString("HTTP_200_Actually_OK ResponseCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP 200 Actually OK. No errors, failed, or exceptions found in response body..
        /// </summary>
        internal static string HTTP_200_Actually_OK_ResponseComments {
            get {
                return ResourceManager.GetString("HTTP_200_Actually_OK ResponseComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 Actually OK.
        /// </summary>
        internal static string HTTP_200_Actually_OK_SessionType {
            get {
                return ResourceManager.GetString("HTTP_200_Actually_OK SessionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENT ACCESS RULE.
        /// </summary>
        internal static string HTTP_200_Client_Access_Rule {
            get {
                return ResourceManager.GetString("HTTP_200_Client Access Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;CLIENT ACCESS RULE&lt;/span&gt;&lt;/b&gt;.
        /// </summary>
        internal static string HTTP_200_Client_Access_Rule_ResponseAlert {
            get {
                return ResourceManager.GetString("HTTP_200_Client Access Rule ResponseAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 OK Client Access Rule.
        /// </summary>
        internal static string HTTP_200_Client_Access_Rule_ResponseCodeDescription {
            get {
                return ResourceManager.GetString("HTTP_200_Client Access Rule ResponseCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;A client access rule has blocked MAPI connectivity to the mailbox&lt;/span&gt;&lt;/b&gt;.&lt;p&gt;Check if the &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;client access rule includes OutlookAnywhere&lt;/span&gt;&lt;/b&gt;.&lt;/p&gt;&lt;p&gt;Per &lt;a href=&apos;https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules&apos; target=&apos;_blank&apos;&gt;https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules&lt;/a&gt;, &lt;br /&gt;OutlookAnywhere includ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTTP_200_Client_Access_Rule_ResponseComments {
            get {
                return ResourceManager.GetString("HTTP_200_Client Access Rule ResponseComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Tunnel.
        /// </summary>
        internal static string HTTP_200_ConnectTunnel {
            get {
                return ResourceManager.GetString("HTTP_200_ConnectTunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an encrypted tunnel. If all or most of the sessions are connect tunnels the sessions collected did not have decryption enabled. Setup Fiddler to &apos;Decrypt HTTPS traffic&apos;, click Tools -&gt; Options -&gt; HTTPS tab.&lt;p&gt;If in any doubt see instructions at https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/DecryptHTTPS. &lt;/p&gt;.
        /// </summary>
        internal static string HTTP_200_ConnectTunnel_RepsonseComments {
            get {
                return ResourceManager.GetString("HTTP_200_ConnectTunnel_RepsonseComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        internal static string Inspector {
            get {
                return ResourceManager.GetString("Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data.
        /// </summary>
        internal static string Insufficient_data {
            get {
                return ResourceManager.GetString("Insufficient data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        internal static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Extension Version.
        /// </summary>
        internal static string Local_Extension_Version {
            get {
                return ResourceManager.GetString("Local Extension Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Ruleset Version.
        /// </summary>
        internal static string Local_Ruleset_Version {
            get {
                return ResourceManager.GetString("Local Ruleset Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locally Installed Information.
        /// </summary>
        internal static string Locally_Installed_Information {
            get {
                return ResourceManager.GetString("Locally Installed Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute ago.
        /// </summary>
        internal static string minute_ago {
            get {
                return ResourceManager.GetString("minute ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        internal static string minutes_ago {
            get {
                return ResourceManager.GetString("minutes ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Identifier Format.
        /// </summary>
        internal static string Name_Identifier_Format {
            get {
                return ResourceManager.GetString("Name Identifier Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Update Check.
        /// </summary>
        internal static string Next_Update_Check {
            get {
                return ResourceManager.GetString("Next Update Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string No_Data {
            get {
                return ResourceManager.GetString("No Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session analysis. Use the &apos;Process All Sessions&apos; option from the Office365 extension menu to get session analysis..
        /// </summary>
        internal static string No_Session_Analysis {
            get {
                return ResourceManager.GetString("No Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obscure Settings.
        /// </summary>
        internal static string Obscure_Settings {
            get {
                return ResourceManager.GetString("Obscure Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365.
        /// </summary>
        internal static string Office_365 {
            get {
                return ResourceManager.GetString("Office 365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365 Fiddler Extension.
        /// </summary>
        internal static string Office_365_Fiddler_Extension {
            get {
                return ResourceManager.GetString("Office 365 Fiddler Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Live Trace.
        /// </summary>
        internal static string On_Live_Trace {
            get {
                return ResourceManager.GetString("On Live Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Load Saz.
        /// </summary>
        internal static string On_Load_Saz {
            get {
                return ResourceManager.GetString("On Load Saz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Demand.
        /// </summary>
        internal static string OnDemand {
            get {
                return ResourceManager.GetString("OnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Session Timers.
        /// </summary>
        internal static string Overall_Session_Timers {
            get {
                return ResourceManager.GetString("Overall Session Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        internal static string Process_Name {
            get {
                return ResourceManager.GetString("Process Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Selected Sessions.
        /// </summary>
        internal static string Recalculate_Selected_Sessions {
            get {
                return ResourceManager.GetString("Recalculate Selected Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        internal static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Capture.
        /// </summary>
        internal static string Remote_Capture {
            get {
                return ResourceManager.GetString("Remote Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issues.
        /// </summary>
        internal static string Report_Issues {
            get {
                return ResourceManager.GetString("Report Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Code.
        /// </summary>
        internal static string Response_Code {
            get {
                return ResourceManager.GetString("Response Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;No known issue with Microsoft365 and this type of session. If you have a suggestion for an improvement, create an issue or better yet a pull request in the project Github repository: &lt;a href=&apos;https://github.com/jprknight/Office365FiddlerExtension&apos; target=&apos;_blank&apos;&gt;https://github.com/jprknight/Office365FiddlerExtension&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string Response_Comments_No_Known_Issue {
            get {
                return ResourceManager.GetString("Response Comments No Known Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Server.
        /// </summary>
        internal static string Response_Server {
            get {
                return ResourceManager.GetString("Response Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAML Response Parser.
        /// </summary>
        internal static string SAML_Response_Parser {
            get {
                return ResourceManager.GetString("SAML Response Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreForSession.
        /// </summary>
        internal static string ScoreForSession {
            get {
                return ResourceManager.GetString("ScoreForSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Begin Response.
        /// </summary>
        internal static string Server_Begin_Response {
            get {
                return ResourceManager.GetString("Server Begin Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Done Response.
        /// </summary>
        internal static string Server_Done_Response {
            get {
                return ResourceManager.GetString("Server Done Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Got Request.
        /// </summary>
        internal static string Server_Got_Request {
            get {
                return ResourceManager.GetString("Server Got Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Think Time.
        /// </summary>
        internal static string Server_Think_Time {
            get {
                return ResourceManager.GetString("Server Think Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Timers.
        /// </summary>
        internal static string Server_Timers {
            get {
                return ResourceManager.GetString("Server Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Age.
        /// </summary>
        internal static string Session_Age {
            get {
                return ResourceManager.GetString("Session Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Analysis.
        /// </summary>
        internal static string Session_Analysis {
            get {
                return ResourceManager.GetString("Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Captured.
        /// </summary>
        internal static string Session_Captured {
            get {
                return ResourceManager.GetString("Session Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;Session collected between 14 and 30 days ago&lt;/span&gt;&lt;/b&gt;. Correlating with any backend server logs is &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;likely impossible&lt;/span&gt;&lt;/b&gt;. Many systems don&apos;t keep logs this long.&lt;/p&gt;.
        /// </summary>
        internal static string Session_collected_between_14_and_30_days_ago {
            get {
                return ResourceManager.GetString("Session collected between 14 and 30 days ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;Session collected more than 30 days ago&lt;/span&gt;&lt;/b&gt;. Correlating with any backend server logs is &lt;b&gt;&lt;span style=&apos;color:red&apos;&gt;very likely impossible&lt;/span&gt;&lt;/b&gt;. Many systems don&apos;t keep logs this long.&lt;/p&gt;.
        /// </summary>
        internal static string Session_collected_more_than_30_days_ago {
            get {
                return ResourceManager.GetString("Session collected more than 30 days ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Session collected within 14 days, data freshness is good, &lt;b&gt;&lt;span style=&apos;color:orange&apos;&gt;but not ideal&lt;/span&gt;&lt;/b&gt;. Depending on the backend system, &lt;b&gt;&lt;span style=&apos;color:orange&apos;&gt; correlating this data to server logs might be possible&lt;/span&gt;&lt;/b&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string Session_collected_within_14_days {
            get {
                return ResourceManager.GetString("Session collected within 14 days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session collected within 7 days, data freshness is good. Best case scenario for correlating this data to backend server logs..
        /// </summary>
        internal static string Session_collected_within_7_days {
            get {
                return ResourceManager.GetString("Session collected within 7 days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Elapsed Time.
        /// </summary>
        internal static string Session_Elapsed_Time {
            get {
                return ResourceManager.GetString("Session Elapsed Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID.
        /// </summary>
        internal static string Session_ID {
            get {
                return ResourceManager.GetString("Session ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Type.
        /// </summary>
        internal static string Session_Type {
            get {
                return ResourceManager.GetString("Session Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The server think time for this session was less than 1/10th of the elapsed time. This indicates network latency in this session.&lt;/p&gt;&lt;p&gt;If you are troubleshooting application latency, the next step is to collect network traces (Wireshark, NetMon etc) and troubleshoot at the network layer.&lt;/p&gt;&lt;p&gt;Ideally collect concurrent network traces on the impacted client and a network perimeter device, to be analysed together by a member of your networking team.&lt;p&gt;.
        /// </summary>
        internal static string SessionTimersDescription {
            get {
                return ResourceManager.GetString("SessionTimersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Session Severity.
        /// </summary>
        internal static string Set_Session_Severity {
            get {
                return ResourceManager.GetString("Set Session Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe.
        /// </summary>
        internal static string Severe {
            get {
                return ResourceManager.GetString("Severe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Session Analysis.
        /// </summary>
        internal static string Simple_Session_Analysis {
            get {
                return ResourceManager.GetString("Simple Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Session Analysis - Json Read Failure..
        /// </summary>
        internal static string Simple_Session_Analysis___Json_Read_Failure_ {
            get {
                return ResourceManager.GetString("Simple Session Analysis - Json Read Failure.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Running Session Threshold.
        /// </summary>
        internal static string Slow_Running_Session_Threshold {
            get {
                return ResourceManager.GetString("Slow Running Session Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Session Analysis.
        /// </summary>
        internal static string Some_Session_Analysis {
            get {
                return ResourceManager.GetString("Some Session Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit Time.
        /// </summary>
        internal static string Transit_Time {
            get {
                return ResourceManager.GetString("Transit Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninteresting.
        /// </summary>
        internal static string Uninteresting {
            get {
                return ResourceManager.GetString("Uninteresting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To Date.
        /// </summary>
        internal static string Up_To_Date {
            get {
                return ResourceManager.GetString("Up To Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string Update_Available {
            get {
                return ResourceManager.GetString("Update Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Session Time Threshold.
        /// </summary>
        internal static string Warning_Session_Time_Threshold {
            get {
                return ResourceManager.GetString("Warning Session Time Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are these two thresholds?.
        /// </summary>
        internal static string What_are_these_two_thresholds {
            get {
                return ResourceManager.GetString("What are these two thresholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is ScoreForSession?.
        /// </summary>
        internal static string What_is_ScoreForSession {
            get {
                return ResourceManager.GetString("What is ScoreForSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
    }
}
